Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"
  config.vm.network "private_network", ip: "192.168.56.11"
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y && apt-get upgrade -y
  SHELL

  config.vm.provision "shell", name: "salt-stack", path: "install_saltstack.sh"
end
