SERVICES = {
  master: {
    ip: '192.168.56.10',
    memory: 1024,
    cpus: 1
  },
  minion_1: {
    ip: '192.168.56.11',
    memory: 512,
    cpus: 1
  },
  minion_2: {
    ip: '192.168.56.12',
    memory: 512,
    cpus: 1
  }
}

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: SERVICES[:master][:ip]
    # master.vm.provision "shell", name: "master-salt", path: "master.sh"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = SERVICES[:master][:memory]
      vb.cpus = SERVICES[:master][:cpus]
    end
  end

  config.vm.define "minion-1" do |minion_1|
    minion_1.vm.hostname = "minion-1"
    minion_1.vm.network "private_network", ip: SERVICES[:minion_1][:ip]
    # minion_1.vm.provision "shell", name: "minion-1-salt", path: "minion.sh"
    minion_1.vm.provider "virtualbox" do |vb|
      vb.memory = SERVICES[:minion_1][:memory]
      vb.cpus = SERVICES[:minion_1][:cpus]
    end
  end

  config.vm.define "minion-2" do |minion_2|
    minion_2.vm.hostname = "minion-2"
    minion_2.vm.network "private_network", ip: SERVICES[:minion_2][:ip]
    # minion_2.vm.provision "shell", name: "minion-2-salt", path: "minion.sh"
    minion_2.vm.provider "virtualbox" do |vb|
      vb.memory = SERVICES[:minion_2][:memory]
      vb.cpus = SERVICES[:minion_2][:cpus]
    end
  end

end
