Vagrant.configure("2") do |config|

  config.vm.box = "kalilinux/rolling"
  config.vm.box_version = "2025.1.0"
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
    vb.cpus = 2 
  end

  config.vm.provision "shell", run: "never", inline: <<-SHELL
    apt-get update -y && apt-get upgrade -y
  SHELL

end
